name: HTB Exam Status Daily Check

off:
  schedule:
    # DST months: March (3) -> October (10) run at 06:00 UTC (= 08:00 CEST)
    - cron: '0 6 * 3-10 *'
    # Standard months: November(11) -> February(2) run at 07:00 UTC (= 08:00 CET)
    - cron: '0 7 * 11-2 *'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  check-exam:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run HTB check script
        env:
          HTB_EMAIL: ${{ secrets.HTB_EMAIL }}
          HTB_PASSWORD: ${{ secrets.HTB_PASSWORD }}
          # optional: if you prefer to use a cookie for Academy access
          HTB_COOKIE: ${{ secrets.HTB_COOKIE }}
          # Mailgun configuration
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
          MAILGUN_TO: ${{ secrets.MAILGUN_TO }}
          MAILGUN_FROM: ${{ secrets.MAILGUN_FROM }}
          # Choose exam: CBBH or CDSA
          HTB_EXAM: ${{ secrets.HTB_EXAM }}
        run: |
          python check_htb_exam.py
