name: Export DNS Records (Dig)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
    paths:
      - 'domains.txt'
      - 'route53_exporter.py'

jobs:
  export_records:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run DNS Exporter Script (Dig)
        run: python route53_exporter.py

      # This step is for debugging and can be removed later
      - name: List generated files
        run: ls -l *-records.csv || echo "No CSV files generated."

      - name: Commit and Push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add *-records.csv
          # The following 'git commit' command will always run.
          # If there are no changes, it will print "nothing to commit".
          # If there are changes, it will commit them.
          git commit -m "Automated: Update DNS records export via dig"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
